// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package advantages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "agency-site/internal/types"

func AdvantagesGrid(advantages []types.AdvantageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section x-data=\"{\r\n\t\t\tscrollProgress: 0,\r\n\t\t\tinit() {\r\n\t\t\t\twindow.addEventListener('scroll', () => {\r\n\t\t\t\t\tconst track = this.$refs.track;\r\n\t\t\t\t\tconst rect = track.getBoundingClientRect();\r\n\t\t\t\t\tconst trackHeight = rect.height - window.innerHeight;\r\n\t\t\t\t\t\r\n\t\t\t\t\tif (trackHeight <= 0) return;\r\n\t\t\t\t\t\r\n\t\t\t\t\t// Calculate progress from 0 (top of section) to 1 (bottom of section)\r\n\t\t\t\t\tlet progress = -rect.top / trackHeight;\r\n\t\t\t\t\tthis.scrollProgress = Math.max(0, Math.min(1, progress));\r\n\t\t\t\t});\r\n\t\t\t}\r\n\t\t}\" x-ref=\"track\" class=\"relative h-[300vh] text-black\"><div class=\"sticky top-0 h-screen w-full flex flex-col justify-center overflow-hidden px-6 sm:px-12 lg:px-24\"><div class=\"max-w-6xl w-full mx-auto mb-12 text-center lg:text-left shrink-0\"><h2 class=\"text-xs font-semibold tracking-widest text-indigo-400 uppercase\">Our Impact</h2><p class=\"mt-2 text-3xl font-bold tracking-tight text-black sm:text-4xl\">Why companies choose to partner with us</p></div><div class=\"max-w-6xl w-full mx-auto relative\"><div class=\"flex gap-8 transition-transform duration-75 ease-out will-change-transform\" :style=\"`transform: translateX(calc(-${scrollProgress * 100}% + ${scrollProgress * 32}rem))`\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, item := range advantages {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"group flex flex-col items-start pt-6 pb-8 pr-8 w-[85vw] sm:w-[45vw] md:w-[30vw] shrink-0 outline-none\"><div class=\"w-full h-[4px] bg-[#a100ff] mb-6 rounded-full origin-left transition-transform duration-500 group-hover:scale-x-110\"></div><span class=\"text-8xl lg:text-9xl font-thin tracking-tight text-[#a100ff] transition-transform duration-300 group-hover:scale-105 select-none\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(item.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/home/advantage-section/advantages.templ`, Line: 44, Col: 20}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span><p class=\"mt-4 text-left text-base lg:text-lg font-normal leading-relaxed text-[#212529] group-hover:text-black\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(item.Content)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/home/advantage-section/advantages.templ`, Line: 47, Col: 22}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
